[[main]]
  name = 'Home'
  pageRef = '/'
  weight = 1
[[main]]
  name = 'Bookmarks'
  pageRef = '/bookmarks'
  weight = 2
[[main]]
  name = 'Articles'
  pageRef = '/articles'
  weight = 3

[[footer]]
  name = 'Contact'
  pageRef = '/contact'
  weight = 10
[[footer]]
  name = 'Copyleft'
  pageRef = '/copyleft'
  weight = 20
[[footer]]
  name = 'Privacy'
  pageRef = '/privacy'
  weight = 30
