[[footer]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[footer]]
  name = 'Articles'
  pageRef = '/articles'
  weight = 20
[[footer]]
  name = 'RSS'
  url = 'https://les.cx/articles/index.xml'
  weight = 30
[[footer]]
  name = 'Contact'
  pageRef = '/contact'
  weight = 40
[[footer]]
  name = 'Copyright'
  pageRef = '/copyright'
  weight = 50
[[footer]]
  name = 'Privacy'
  pageRef = '/privacy'
  weight = 60
